<?php
    if ($block->isPromotionsActiveForCart()) {
?>
<script>
var tabbyConfig = <?php echo $block->getJsonConfigTabby('#tabbyPromo'); ?>;
function updateTabbyPromotions(price) {
    if (price != tabbyConfig.price) {
        document.querySelector('#tabbyPromo').innerHTML = '';
        tabbyConfig.price = price * tabbyConfig.currencyRate;
        new window.TabbyPromo(tabbyConfig);
    }
}
require(['Magento_Checkout/js/model/quote'], function (quote) {
    quote.getTotals().subscribe(function (totals) {
        let price = totals.grand_total + totals.tax_amount;
        updateTabbyPromotions(price);
    });
});
</script>
<div id="tabbyPromo">
</div>
<?php
    };
?>
