<?php
if ($block->isPromotionsActiveForCart()):
    ?>
    <script>
        var tabbyConfig = <?= /* @noEscape */ $block->getJsonConfigTabby('#tabbyPromo'); ?>;

        function updateTabbyPromotions(price) {
            if (price != tabbyConfig.price) {
                tabbyConfig.price = price * tabbyConfig.currencyRate;
                new window.TabbyPromo(tabbyConfig);
            }
        }

        require(['Magento_Checkout/js/model/quote'], function (quote) {
console.log(quote);
            function updateTabbyTotal(totals) {
console.log(totals);
                let price = parseFloat(totals.grand_total);
                updateTabbyPromotions(price);
            };
            quote.getTotals().subscribe(updateTabbyTotal);
            updateTabbyTotal(quote.getTotals()());
        });
    </script>
    <div id="tabbyPromo">
    </div>
<?php endif; ?>
